/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interpolacion;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.nfunk.jep.JEP;

/**
 *
 * @author Usuario
 */
public class Newton extends javax.swing.JFrame {
    private String[] args;
    private String funcion;
    private double x;
    private double x0;
    private double x1;
    private double x2;
    private double valorAproximado;
    private double valorVerdadero;
    private double errorAbsoluto;
    private double errorRelativoPorcentual;
    private final ArrayList<Double> cordenadasx;
    private final ArrayList<Double> cordenadasy;
    
    /**
     * Creates new form InterpolacionNewton
     */
    public Newton() {
        args = null;
        x  = (double) 0.0;
        x0 = (double) 0.0;
        x1 = (double) 0.0;
        x2 = (double) 0.0;
        funcion = "";
        valorAproximado  = (double) 0.0;
        valorVerdadero  = (double) 0.0;
        errorAbsoluto  = (double) 0.0;
        errorRelativoPorcentual  = (double) 0.0;
        cordenadasx = new ArrayList<Double>();
        cordenadasy = new ArrayList<Double>();
        initComponents();
        txtX2.setEditable(false);
        txtValorAproximado.setEditable(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblInterpolacion = new javax.swing.JLabel();
        cboInterpolacion = new javax.swing.JComboBox();
        btnVolver = new javax.swing.JButton();
        lblFuncion = new javax.swing.JLabel();
        lblFuncionEj = new javax.swing.JLabel();
        txtFuncion = new javax.swing.JTextField();
        lblX = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        txtX2 = new javax.swing.JTextField();
        lblX0 = new javax.swing.JLabel();
        txtX0 = new javax.swing.JTextField();
        lblX1 = new javax.swing.JLabel();
        txtX1 = new javax.swing.JTextField();
        lblX2 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        txtValorAproximado = new javax.swing.JTextField();
        lblValorVerdadero = new javax.swing.JLabel();
        lblEj1 = new javax.swing.JLabel();
        lblEj2 = new javax.swing.JLabel();
        lblEj3 = new javax.swing.JLabel();
        lblEj4 = new javax.swing.JLabel();
        lblValorAproximado = new javax.swing.JLabel();
        lblErrorAbsoluto = new javax.swing.JLabel();
        lblErrorRelativoPorcentual = new javax.swing.JLabel();
        txtValorVerdadero = new javax.swing.JTextField();
        txtErrorAbsoluto = new javax.swing.JTextField();
        txtErrorRelativoPorcentual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpFondo.setBackground(new java.awt.Color(51, 102, 255));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setText("Polinomios interpolantes de Newton");

        lblInterpolacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblInterpolacion.setText("Interpolacion:");

        cboInterpolacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lineal", "Cuadrática" }));
        cboInterpolacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboInterpolacionActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        lblFuncion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFuncion.setText("Función a evaluar:");

        lblFuncionEj.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFuncionEj.setText("Ejemplos:");

        lblX.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblX.setText("X = ");

        txtX.setPreferredSize(new java.awt.Dimension(50, 50));

        txtX2.setPreferredSize(new java.awt.Dimension(50, 50));

        lblX0.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblX0.setText("X0=");

        txtX0.setPreferredSize(new java.awt.Dimension(50, 50));

        lblX1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblX1.setText("X1=");

        txtX1.setPreferredSize(new java.awt.Dimension(50, 50));

        lblX2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblX2.setText("X2=");

        btnCalcular.setText("Calcular");
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMouseClicked(evt);
            }
        });

        lblValorVerdadero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValorVerdadero.setText("Valor Verdadero");

        lblEj1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEj1.setText("ln(x)");

        lblEj2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEj2.setText("sin(x)");

        lblEj3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEj3.setText("e^x");

        lblEj4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEj4.setText("cos(pi*x)");

        lblValorAproximado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValorAproximado.setText("Valor Aproximado");

        lblErrorAbsoluto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblErrorAbsoluto.setText("Error Absoluto");

        lblErrorRelativoPorcentual.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblErrorRelativoPorcentual.setText("Error Relativo %");

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(lblInterpolacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboInterpolacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFuncion)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(lblX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(txtFuncion)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpFondoLayout.createSequentialGroup()
                                .addComponent(lblX0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtX0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpFondoLayout.createSequentialGroup()
                                .addComponent(lblX1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpFondoLayout.createSequentialGroup()
                                .addComponent(lblX2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(btnCalcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblErrorAbsoluto)
                                            .addComponent(lblEj3)
                                            .addGroup(jpFondoLayout.createSequentialGroup()
                                                .addComponent(lblErrorRelativoPorcentual)
                                                .addGap(21, 21, 21)
                                                .addComponent(txtErrorRelativoPorcentual, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnVolver))
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpFondoLayout.createSequentialGroup()
                                                .addGap(203, 203, 203)
                                                .addComponent(lblEj4))
                                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtErrorAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                                        .addComponent(lblEj1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblEj2))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpFondoLayout.createSequentialGroup()
                                                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(lblFuncionEj)
                                                            .addComponent(lblValorAproximado))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtValorAproximado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                                        .addComponent(lblValorVerdadero)
                                                        .addGap(19, 19, 19)
                                                        .addComponent(txtValorVerdadero)))))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(15, 15, 15))))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInterpolacion)
                    .addComponent(cboInterpolacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncion)
                    .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFuncionEj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblX)
                    .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEj1)
                    .addComponent(lblEj2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtX0, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblX0)
                    .addComponent(lblEj4)
                    .addComponent(lblEj3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblX1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblX2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorAproximado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorAproximado))
                        .addGap(10, 10, 10)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorVerdadero)
                            .addComponent(txtValorVerdadero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtErrorAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorAbsoluto))
                .addGap(10, 10, 10)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErrorRelativoPorcentual)
                    .addComponent(btnCalcular)
                    .addComponent(btnVolver)
                    .addComponent(txtErrorRelativoPorcentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        Menu.main(args);
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void cboInterpolacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboInterpolacionActionPerformed
        if(cboInterpolacion.getSelectedItem().equals("Lineal")){
            txtX2.setText("");
            txtX2.setEditable(false);
        }
        else
            txtX2.setEditable(true);
    }//GEN-LAST:event_cboInterpolacionActionPerformed

    private void btnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseClicked
        txtValorAproximado.setText("");
        txtValorVerdadero.setText("");
        txtErrorAbsoluto.setText("");
        txtErrorRelativoPorcentual.setText("");
        funcion = txtFuncion.getText();
        
        
        if(funcionValida() && valoresValidos()){
            if(cboInterpolacion.getSelectedItem().equals("Lineal")){
                valorAproximado = interpolacionLineal();
            }else{
                valorAproximado = interpolacionCuadratica();
            }
            valorVerdadero = F(x);
            errorAbsoluto = errorAbsoluto();
            errorRelativoPorcentual = errorRelativoPorcentual();
            mostrarResultados();
            cargarcordenadas();
            PintarGraficas gnewton=new PintarGraficas(funcion,"INTERPOLACION NEWTON",cordenadasx, cordenadasy);
            gnewton.setVisible(true);
            Pintarvavv gnewtonvavv=new Pintarvavv(funcion,x,valorAproximado,valorVerdadero);
            gnewtonvavv.setVisible(true);
        }
    }//GEN-LAST:event_btnCalcularMouseClicked

    
    public boolean funcionValida(){
        
        JEP parseador = new JEP();
       
        parseador.setImplicitMul(true); 
        parseador.addStandardFunctions();
        parseador.addStandardConstants();
        parseador.addVariable("x",0);
        parseador.parseExpression(funcion);
        
        if(parseador.hasError()){
            JOptionPane.showMessageDialog(this, "Expresión inválida");
            return false;
        }
        return true;
    }
    
    public boolean valoresValidos(){
        
        if(this.txtX.getText().equalsIgnoreCase("") || this.txtX0.getText().equalsIgnoreCase("") || 
           this.txtX1.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Valores incompletos");
            return false;
        }
        
        
        
        if(this.txtX.getText().equalsIgnoreCase("pi") || this.txtX.getText().equalsIgnoreCase("e")){
            if(this.txtX.getText().equalsIgnoreCase("pi"))
                x = 3.141592653589793;
            else
                x = 2.718281828459045;
                
        }else{
            try{
                x = Double.parseDouble(this.txtX.getText());
                    
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "El valor de X es inválido");
                return false;
            }
        }
        
        if(this.txtX0.getText().equalsIgnoreCase("pi") || this.txtX0.getText().equalsIgnoreCase("e")){
            if(this.txtX0.getText().equalsIgnoreCase("pi"))
                x0 = 3.141592653589793;
            else
                x0 = 2.718281828459045;
                
        }else{
            try{
                x0 = Double.parseDouble(this.txtX0.getText());
                    
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "El valor de X0 es inválido");
                return false;
            }
        }
        
        if(this.txtX1.getText().equalsIgnoreCase("pi") || this.txtX1.getText().equalsIgnoreCase("e")){
            if(this.txtX1.getText().equalsIgnoreCase("pi"))
                x1 = 3.141592653589793;
            else
                x1 = 2.718281828459045;
                
        }else{
            try{
                x1 = Double.parseDouble(this.txtX1.getText());
                    
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "El valor de X1 es inválido");
                return false;
            }
        }
        
        if(cboInterpolacion.getSelectedItem().equals("Cuadrática")){
            if(this.txtX2.getText().equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Valores incompletos");
                return false;
            }
            
            if(this.txtX2.getText().equalsIgnoreCase("pi") || this.txtX2.getText().equalsIgnoreCase("e")){
                if(this.txtX2.getText().equalsIgnoreCase("pi"))
                    x2 = 3.141592653589793;
                else
                    x2 = 2.718281828459045;
                
            }else{
                try{
                    x2 = Double.parseDouble(this.txtX2.getText());
                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, "El valor de X2 es inválido");
                    return false;
                }
            }
            
            if(!((x0<x1)&&(x1<x2))){
                JOptionPane.showMessageDialog(this, "Los valores ingresados deben estar ordenados\n"
                                                  + "de menor a mayor es decir X0<X1<X2");
                return false;
            }
            
            if(x<x0 || x>x2){
                JOptionPane.showMessageDialog(this, "El valor de X debe estar entre X0 y X2");
                return false;
            }
        }else{
            
            if(!(x0<x1)){
                JOptionPane.showMessageDialog(this, "Los valores ingresados deben estar ordenados\n"
                                                  + "de menor a mayor es decir X0<X1");
                return false;
            }
            
            if(x<x0 || x>x1){
                JOptionPane.showMessageDialog(this, "El valor de X debe estar entre X0 y X1");
                return false;
            }      
        }
        
        
        
        if(txtX.getText().equalsIgnoreCase(txtX0.getText()) || txtX.getText().equalsIgnoreCase(txtX1.getText()) || 
           txtX.getText().equalsIgnoreCase(txtX2.getText()) || txtX0.getText().equalsIgnoreCase(txtX1.getText())||
           txtX0.getText().equalsIgnoreCase(txtX2.getText())|| txtX1.getText().equalsIgnoreCase(txtX2.getText()) ){
            
            JOptionPane.showMessageDialog(this, "Los valores de X X0 X1 X2 deben ser distintos");
            return false;
        }
        
        
        return true;
    }
    
    
    
    public double F(double x){
        
        JEP parseador = new JEP();
        
        double resultado;
        
        parseador.setImplicitMul(true); 
        parseador.addStandardFunctions();
        parseador.addStandardConstants();
        parseador.addVariable("x", x);
        parseador.parseExpression(funcion);
        
        resultado = parseador.getValue();
        
        //JOptionPane.showMessageDialog(this, "f("+x+") = "+" "+resultado);
        
        return resultado;
    }
    
    public double interpolacionLineal(){
        double resultado;
        
        resultado = F(x0)+((F(x1)-F(x0))/(x1-x0))*(x-x0);
        
        return resultado;
    }
    
    public double interpolacionCuadratica(){
        double resultado;
        double b0,b1,b2;
        
        b0 = F(x0);
        
        b1 = (F(x1)-F(x0))/(x1-x0);
        
        b2 = (((F(x2)-F(x1))/(x2-x1))-((F(x1)-F(x0))/(x1-x0)))/(x2-x0);
        
        resultado = b0 + b1*(x-x0) + b2*(x-x0)*(x-x1);
        
        return resultado;
    
    }
    
    public double errorAbsoluto(){
        double errorAbsoluto = Math.abs(valorVerdadero - valorAproximado);
        
        return errorAbsoluto;
    }
    
    public double errorRelativoPorcentual(){
        double errorRelativoPorcentual = Math.abs(errorAbsoluto/valorVerdadero) * 100;
        
        return errorRelativoPorcentual;
    }
    
    public void mostrarResultados(){
        
        //Para mostrar solo 6 decimales, menos el ERP% que solo muestra 3
        valorAproximado = (Math.round(valorAproximado *1000000.0)/1000000.0);  
        valorVerdadero = (Math.round(valorVerdadero *1000000.0)/1000000.0);  
        errorAbsoluto = (Math.round(errorAbsoluto *1000000.0)/1000000.0);  
        errorRelativoPorcentual = (Math.round(errorRelativoPorcentual *1000.0)/1000.0);
        
        txtValorAproximado.setText(Double.toString(valorAproximado));
        txtValorVerdadero.setText(Double.toString(valorVerdadero));
        txtErrorAbsoluto.setText(Double.toString(errorAbsoluto));
        txtErrorRelativoPorcentual.setText(Double.toString(errorRelativoPorcentual)+" %");
    }
    
    public void cargarcordenadas(){
         double j, f = x1;
         if(x1 < x2)f = x2;
         for(j = x0 ; j < f ; j = j + 0.05){
            cordenadasx.add(j);
            cordenadasy.add(F(j));
         }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox cboInterpolacion;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JLabel lblEj1;
    private javax.swing.JLabel lblEj2;
    private javax.swing.JLabel lblEj3;
    private javax.swing.JLabel lblEj4;
    private javax.swing.JLabel lblErrorAbsoluto;
    private javax.swing.JLabel lblErrorRelativoPorcentual;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblFuncionEj;
    private javax.swing.JLabel lblInterpolacion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorAproximado;
    private javax.swing.JLabel lblValorVerdadero;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblX0;
    private javax.swing.JLabel lblX1;
    private javax.swing.JLabel lblX2;
    private javax.swing.JTextField txtErrorAbsoluto;
    private javax.swing.JTextField txtErrorRelativoPorcentual;
    private javax.swing.JTextField txtFuncion;
    private javax.swing.JTextField txtValorAproximado;
    private javax.swing.JTextField txtValorVerdadero;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtX0;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX2;
    // End of variables declaration//GEN-END:variables
}
